import type { Restaurant } from '@/services/restaurants/restaurant.interface';
import type { Category } from '@/services/menu/menu.interface';
import type { MenuItem } from '@/services/menu/menu.interface';
import type {
  Order,
  OrderWithDetails,
} from '@/services/orders/order.interface';

export const mockRestaurants: Restaurant[] = [
  {
    restaurant_id: '1',
    name: 'The Golden Spoon',
    description: 'Fine dining experience with authentic Vietnamese cuisine',
    address_details: '123 Nguyen Hue St, District 1, Ho Chi Minh City',
    status: 'OPEN',
    rating: 4.5,
    total_reviews: 128,
    image_url:
      'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
    registration_date: '2024-01-15',
  },
  {
    restaurant_id: '2',
    name: 'Pho Heaven',
    description: 'Traditional Vietnamese pho and noodle dishes',
    address_details: '456 Le Loi St, District 1, Ho Chi Minh City',
    status: 'OPEN',
    rating: 4.8,
    total_reviews: 256,
    image_url:
      'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    registration_date: '2023-11-20',
  },
  {
    restaurant_id: '3',
    name: 'Pizza Paradise',
    description: 'Authentic Italian pizza made with fresh ingredients',
    address_details: '789 Pasteur St, District 3, Ho Chi Minh City',
    status: 'BUSY',
    rating: 4.3,
    total_reviews: 89,
    image_url:
      'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
    registration_date: '2024-02-10',
  },
  {
    restaurant_id: '4',
    name: 'Sushi Master',
    description: 'Fresh sushi and Japanese cuisine',
    address_details: '321 Dong Khoi St, District 1, Ho Chi Minh City',
    status: 'OPEN',
    rating: 4.7,
    total_reviews: 203,
    image_url:
      'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800',
    registration_date: '2023-12-05',
  },
  {
    restaurant_id: '5',
    name: 'Burger Brothers',
    description: 'Gourmet burgers and American classics',
    address_details: '567 Hai Ba Trung St, District 3, Ho Chi Minh City',
    status: 'OPEN',
    rating: 4.2,
    total_reviews: 167,
    image_url:
      'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800',
    registration_date: '2024-03-01',
  },
  {
    restaurant_id: '6',
    name: 'Thai Spice',
    description: 'Authentic Thai food with bold flavors',
    address_details: '890 Tran Hung Dao St, District 5, Ho Chi Minh City',
    status: 'CLOSED',
    rating: 4.6,
    total_reviews: 145,
    image_url:
      'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800',
    registration_date: '2023-10-15',
  },
  {
    restaurant_id: '7',
    name: 'Cafe Mocha',
    description: 'Coffee, pastries, and light meals',
    address_details:
      '234 Nguyen Thi Minh Khai St, District 1, Ho Chi Minh City',
    status: 'OPEN',
    rating: 4.4,
    total_reviews: 312,
    image_url:
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800',
    registration_date: '2023-09-20',
  },
  {
    restaurant_id: '8',
    name: 'Dragon Wok',
    description: 'Chinese cuisine and dim sum',
    address_details: '678 Le Thanh Ton St, District 1, Ho Chi Minh City',
    status: 'OPEN',
    rating: 4.1,
    total_reviews: 98,
    image_url:
      'https://images.unsplash.com/photo-1526318896980-cf78c088247c?w=800',
    registration_date: '2024-01-08',
  },
];

export const mockCategories: Category[] = [
  { name: 'Vietnamese' },
  { name: 'Japanese' },
  { name: 'Italian' },
  { name: 'American' },
  { name: 'Thai' },
  { name: 'Chinese' },
  { name: 'Cafe' },
  { name: 'Fast Food' },
  { name: 'Desserts' },
  { name: 'Beverages' },
];

export const mockMenuItems: MenuItem[] = [
  {
    food_id: '1',
    restaurant_id: '1',
    name: 'Pho Bo',
    description: 'Traditional beef noodle soup with fresh herbs',
    price: 85000,
    status: 'AVAILABLE',
    category: 'Vietnamese',
  },
  {
    food_id: '2',
    restaurant_id: '1',
    name: 'Banh Mi',
    description: 'Vietnamese sandwich with pate and pickled vegetables',
    price: 45000,
    status: 'AVAILABLE',
    category: 'Vietnamese',
  },
  {
    food_id: '3',
    restaurant_id: '1',
    name: 'Spring Rolls',
    description: 'Fresh spring rolls with shrimp and vegetables',
    price: 65000,
    status: 'AVAILABLE',
    category: 'Vietnamese',
  },
  {
    food_id: '4',
    restaurant_id: '4',
    name: 'Salmon Sushi Set',
    description: '8 pieces of fresh salmon sushi',
    price: 250000,
    status: 'AVAILABLE',
    category: 'Japanese',
  },
  {
    food_id: '5',
    restaurant_id: '4',
    name: 'California Roll',
    description: 'Classic California roll with crab and avocado',
    price: 150000,
    status: 'AVAILABLE',
    category: 'Japanese',
  },
  {
    food_id: '6',
    restaurant_id: '3',
    name: 'Margherita Pizza',
    description: 'Classic pizza with tomato sauce, mozzarella, and basil',
    price: 180000,
    status: 'AVAILABLE',
    category: 'Italian',
  },
  {
    food_id: '7',
    restaurant_id: '3',
    name: 'Pepperoni Pizza',
    description: 'Pizza topped with pepperoni and cheese',
    price: 200000,
    status: 'AVAILABLE',
    category: 'Italian',
  },
  {
    food_id: '8',
    restaurant_id: '5',
    name: 'Classic Burger',
    description: 'Beef burger with lettuce, tomato, and special sauce',
    price: 120000,
    status: 'AVAILABLE',
    category: 'American',
  },
];

export const mockOrders: Order[] = [
  {
    order_id: '1',
    customer_id: 'customer1',
    restaurant_id: '1',
    delivery_id: 'addr1',
    status: 'DELIVERED',
    ordered_at: '2024-12-01T10:30:00',
    confirmed_at: '2024-12-01T10:32:00',
    delivered_at: '2024-12-01T11:15:00',
    restaurant_name: 'The Golden Spoon',
    restaurant_address: '123 Nguyen Hue St, District 1, Ho Chi Minh City',
    delivery_address: '123 Main St, District 1, Ho Chi Minh City',
    recipient_name: 'John Doe',
    recipient_phone: '0901234567',
    payment_type: 'BANK_CARD',
    subtotal: 215000,
    delivery_fee: 25000,
    discount: 0,
    total: 240000,
  },
  {
    order_id: '2',
    customer_id: 'customer1',
    restaurant_id: '4',
    delivery_id: 'addr1',
    status: 'DELIVERING',
    ordered_at: '2024-12-03T12:00:00',
    confirmed_at: '2024-12-03T12:05:00',
    restaurant_name: 'Sushi Master',
    restaurant_address: '321 Dong Khoi St, District 1, Ho Chi Minh City',
    delivery_address: '123 Main St, District 1, Ho Chi Minh City',
    recipient_name: 'John Doe',
    recipient_phone: '0901234567',
    payment_type: 'E_WALLET',
    subtotal: 400000,
    delivery_fee: 30000,
    discount: 0,
    total: 430000,
  },
  {
    order_id: '3',
    customer_id: 'customer1',
    restaurant_id: '3',
    delivery_id: 'addr1',
    status: 'PREPARING',
    ordered_at: '2024-12-03T13:30:00',
    confirmed_at: '2024-12-03T13:32:00',
    restaurant_name: 'Pizza Paradise',
    restaurant_address: '789 Pasteur St, District 3, Ho Chi Minh City',
    delivery_address: '123 Main St, District 1, Ho Chi Minh City',
    recipient_name: 'John Doe',
    recipient_phone: '0901234567',
    payment_type: 'CASH',
    subtotal: 380000,
    delivery_fee: 25000,
    discount: 20000,
    total: 385000,
  },
  {
    order_id: '4',
    customer_id: 'customer1',
    restaurant_id: '2',
    delivery_id: 'addr1',
    status: 'PLACED',
    ordered_at: '2024-12-04T09:15:00',
    restaurant_name: 'Pho Heaven',
    restaurant_address: '456 Le Loi St, District 1, Ho Chi Minh City',
    delivery_address: '123 Main St, District 1, Ho Chi Minh City',
    recipient_name: 'John Doe',
    recipient_phone: '0901234567',
    payment_type: 'BANK_CARD',
    subtotal: 170000,
    delivery_fee: 20000,
    discount: 0,
    total: 190000,
  },
  {
    order_id: '5',
    customer_id: 'customer1',
    restaurant_id: '5',
    delivery_id: 'addr1',
    status: 'CANCELLED',
    ordered_at: '2024-11-30T14:20:00',
    restaurant_name: 'Burger Brothers',
    restaurant_address: '567 Hai Ba Trung St, District 3, Ho Chi Minh City',
    delivery_address: '123 Main St, District 1, Ho Chi Minh City',
    recipient_name: 'John Doe',
    recipient_phone: '0901234567',
    payment_type: 'CASH',
    subtotal: 240000,
    delivery_fee: 25000,
    discount: 0,
    total: 265000,
  },
];

export const mockOrderDetails: OrderWithDetails[] = [
  {
    order_id: '1',
    customer_id: 'customer1',
    restaurant_id: '1',
    delivery_id: 'addr1',
    status: 'DELIVERED',
    ordered_at: '2024-12-01T10:30:00',
    confirmed_at: '2024-12-01T10:32:00',
    delivered_at: '2024-12-01T11:15:00',
    restaurant_name: 'The Golden Spoon',
    restaurant_address: '123 Nguyen Hue St, District 1, Ho Chi Minh City',
    delivery_address: '123 Main St, District 1, Ho Chi Minh City',
    recipient_name: 'John Doe',
    recipient_phone: '0901234567',
    payment_type: 'BANK_CARD',
    subtotal: 215000,
    delivery_fee: 25000,
    discount: 0,
    total: 240000,
    items: [
      {
        item_id: '1',
        order_id: '1',
        food_id: '1',
        item_name: 'Pho Bo',
        quantity: 2,
        price: 85000,
      },
      {
        item_id: '2',
        order_id: '1',
        food_id: '2',
        item_name: 'Banh Mi',
        quantity: 1,
        price: 45000,
      },
    ],
  },
  {
    order_id: '2',
    customer_id: 'customer1',
    restaurant_id: '4',
    delivery_id: 'addr1',
    status: 'DELIVERING',
    ordered_at: '2024-12-03T12:00:00',
    confirmed_at: '2024-12-03T12:05:00',
    restaurant_name: 'Sushi Master',
    restaurant_address: '321 Dong Khoi St, District 1, Ho Chi Minh City',
    delivery_address: '123 Main St, District 1, Ho Chi Minh City',
    recipient_name: 'John Doe',
    recipient_phone: '0901234567',
    payment_type: 'E_WALLET',
    subtotal: 400000,
    delivery_fee: 30000,
    discount: 0,
    total: 430000,
    items: [
      {
        item_id: '3',
        order_id: '2',
        food_id: '4',
        item_name: 'Salmon Sushi Set',
        quantity: 1,
        price: 250000,
      },
      {
        item_id: '4',
        order_id: '2',
        food_id: '5',
        item_name: 'California Roll',
        quantity: 1,
        price: 150000,
      },
    ],
  },
  {
    order_id: '3',
    customer_id: 'customer1',
    restaurant_id: '3',
    delivery_id: 'addr1',
    status: 'PREPARING',
    ordered_at: '2024-12-03T13:30:00',
    confirmed_at: '2024-12-03T13:32:00',
    restaurant_name: 'Pizza Paradise',
    restaurant_address: '789 Pasteur St, District 3, Ho Chi Minh City',
    delivery_address: '123 Main St, District 1, Ho Chi Minh City',
    recipient_name: 'John Doe',
    recipient_phone: '0901234567',
    payment_type: 'CASH',
    subtotal: 380000,
    delivery_fee: 25000,
    discount: 20000,
    total: 385000,
    items: [
      {
        item_id: '5',
        order_id: '3',
        food_id: '6',
        item_name: 'Margherita Pizza',
        quantity: 1,
        price: 180000,
      },
      {
        item_id: '6',
        order_id: '3',
        food_id: '7',
        item_name: 'Pepperoni Pizza',
        quantity: 1,
        price: 200000,
      },
    ],
  },
  {
    order_id: '4',
    customer_id: 'customer1',
    restaurant_id: '2',
    delivery_id: 'addr1',
    status: 'PLACED',
    ordered_at: '2024-12-04T09:15:00',
    restaurant_name: 'Pho Heaven',
    restaurant_address: '456 Le Loi St, District 1, Ho Chi Minh City',
    delivery_address: '123 Main St, District 1, Ho Chi Minh City',
    recipient_name: 'John Doe',
    recipient_phone: '0901234567',
    payment_type: 'BANK_CARD',
    subtotal: 170000,
    delivery_fee: 20000,
    discount: 0,
    total: 190000,
    items: [
      {
        item_id: '7',
        order_id: '4',
        food_id: '1',
        item_name: 'Pho Bo',
        quantity: 2,
        price: 85000,
      },
    ],
  },
  {
    order_id: '5',
    customer_id: 'customer1',
    restaurant_id: '5',
    delivery_id: 'addr1',
    status: 'CANCELLED',
    ordered_at: '2024-11-30T14:20:00',
    restaurant_name: 'Burger Brothers',
    restaurant_address: '567 Hai Ba Trung St, District 3, Ho Chi Minh City',
    delivery_address: '123 Main St, District 1, Ho Chi Minh City',
    recipient_name: 'John Doe',
    recipient_phone: '0901234567',
    payment_type: 'CASH',
    subtotal: 240000,
    delivery_fee: 25000,
    discount: 0,
    total: 265000,
    items: [
      {
        item_id: '8',
        order_id: '5',
        food_id: '8',
        item_name: 'Classic Burger',
        quantity: 2,
        price: 120000,
      },
    ],
  },
];
